### ISSUE TITLE
Pin 0 Error in ESPHome

### ISSUE THREAD

**Issue by Biztactix-Ryan** [haade-administrator/korvo-esphome#2]
Trying to install using your documentation using ESPHome, 
Getting Pin 0 is used multiple times
![image](https://github.com/haade-administrator/korvo-esphome/assets/357433/e922b6c0-4457-4eff-ac62-2cf7a8160500)

**Comment by haade-administrator** [comment]
what is you're version of esphome
give me you're esp32korvo_esphome.yaml of use

**Comment by Biztactix-Ryan** [comment]
Running ESP Home 2023.12.9 which is apparently the latest.
and I just copied and pasted the info from the blog.
the Remote Package should just pull directly from your github right?

Copying and pasting in the ESPHome yaml file from the repo I get the following
![image](https://github.com/haade-administrator/korvo-esphome/assets/357433/6a53404b-5a37-4aff-83ca-69c79e1f852c)

My ESPHome Yaml file
```
substitutions:
  device_name: "voiceassistant1" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  apikey: "A4oH0Ta3ZhVQ77Csr2o/xysQZzJ4fEy5BwXP3mHCUnA="


packages:
  ##### download esp32-korvo for esphome code from Github
  remote_package:
    url: https://github.com/haade-administrator/korvo-esphome
    ref: main
    files: [esp32korvo_esphome.yaml]
    refresh: 300s
```
